/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as EsquadraoRouteImport } from './routes/esquadrao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsquadraoRoute = EsquadraoRouteImport.update({
  id: '/esquadrao',
  path: '/esquadrao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/esquadrao': typeof EsquadraoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/esquadrao': typeof EsquadraoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/esquadrao': typeof EsquadraoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/produto/$slug' | '/esquadrao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/produto/$slug' | '/esquadrao'
  id: '__root__' | '/' | '/produto/$slug' | '/esquadrao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  EsquadraoRoute: typeof EsquadraoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esquadrao': {
      id: '/esquadrao'
      path: '/esquadrao'
      fullPath: '/esquadrao'
      preLoaderRoute: typeof EsquadraoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  EsquadraoRoute: EsquadraoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
